### DISCUSSION TITLE
get_route_path() not handling 'app_root_path'

### DISCUSSION THREAD

**Discussion by karmaBonfire** [encode/starlette#2928] [Potential Issue]
Consider this setup:
- a reverse proxy at `localhost:9999` that strips prefix `/foo` from the path, e. g. `/foo/bar/login` -> `/bar/login`
- a following FastAPI app at `localhost:8000`:
```python
from fastapi import FastAPI, Response
import uvicorn

def setup_app():
    app = FastAPI(
        root_path='/foo'
    )

    layer = FastAPI()
    layer.add_route('/login', lambda _: Response('hello, world'), methods=['GET'])

    app.mount('/bar', layer)
    return app


app = setup_app()


if __name__ == "__main__":
    uvicorn.run('app:app', host='0.0.0.0', port=8000)
```

Querying a reverse proxy (traefik in my case), I expected `GET /foo/bar/login` to produce `'hello, world'` response. However, this app returns 404 Not Found. I managed to identify the issue and made a dirty fix, however, I'm not sure if this is a bug or a user error.

At some point during routing, `score['root_path']` contains a `scope['app_root_path']`, while `scope['path']` does not (since it was replaced by reverse proxy), as shown below (reproduce by setting a breakpoint on line `match, child_scope = route.matches(scope)` in `Router.app()`)
![изображение](https://github.com/user-attachments/assets/38cc390e-590c-4301-9078-126430ea4e87)

My dirty fix adds code that handles this case to `starlette._utils.get_route_path()`:
```python
def get_route_path(scope: Scope) -> str:
    path: str = scope["path"]
    root_path = scope.get("root_path", "")
    if not root_path:
        return path

    # new code
    app_root_path = scope.get("app_root_path", "")
    if app_root_path and root_path.startswith(app_root_path):
        root_path = root_path[len(app_root_path):]

    if not path.startswith(root_path):
        return path

    if path == root_path:
        return ""

    if path[len(root_path)] == "/":
        return path[len(root_path):]

    return path
```

**Comment by karmaBonfire** [comment]
Here's my traefik configuration if you wish to debug this - create these files near traefik executable and run `./traefik`

traefik.toml
```toml
[entryPoints]
  [entryPoints.http]
    address = ":9999"

[providers]
  [providers.file]
    filename = "routes.toml"
```

routes.toml
```toml
[http]
  [http.middlewares]
    [http.middlewares.test-replacepathregex.replacePathRegex]
      regex = "^/foo(.*)"
      replacement = "$1"

  [http.routers]

    [http.routers.app-http]
      entryPoints = ["http"]
      service = "app"
      rule = "PathPrefix(`/foo`)"
      middlewares = ["test-replacepathregex"]

  [http.services]

    [http.services.app]
      [http.services.app.loadBalancer]
        [[http.services.app.loadBalancer.servers]]
          url = "http://127.0.0.1:8000"
```
